security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingwinstar/config-repo
  application:
    name: springcloud-config-server
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
    healthcheck:
      enable: true




     