security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingwinstar/config-repo




     