server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingwinstar/config-repo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest




     